StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EFAB4DB757D12CF}" {
   Id "PS-EditableEntity_MapMarker"
   Target_en_us "Map marker"
   Modified 1593489391
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA5214AF88}" {
   Id "PS-EditorAttribute_Marker_Color"
   Target_en_us "Color"
   Modified 1593489081
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA558B44D8}" {
   Id "PS-EditorAttribute_Marker_Color_Description"
   Modified 1593488868
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA6624ABEE}" {
   Id "PS-EditorAttribute_Marker_Description"
   Target_en_us "Description"
   Modified 1593489077
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA696CE726}" {
   Id "PS-EditorAttribute_Marker_Description_Description"
   Modified 1593488907
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA2EAC6744}" {
   Id "PS-EditorAttribute_Marker_Factions"
   Target_en_us "Show to factions"
   Modified 1593489068
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA303E8D41}" {
   Id "PS-EditorAttribute_Marker_Factions_Description"
   Modified 1593489034
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA4108EB73}" {
   Id "PS-EditorAttribute_Marker_Image"
   Target_en_us "Icon"
   Modified 1593489062
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA44D2E2E4}" {
   Id "PS-EditorAttribute_Marker_Image_Description"
   Modified 1593488840
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA7D15958C}" {
   Id "PS-EditorAttribute_Marker_Size"
   Target_en_us "Size"
   Modified 1593489056
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA0000BFAE}" {
   Id "PS-EditorAttribute_Marker_Size_Description"
   Modified 1593488945
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA1785FE5B}" {
   Id "PS-EditorAttribute_Marker_UseWorldScale"
   Target_en_us "Use world scale"
   Modified 1593489053
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFAB4DA1ADBC740}" {
   Id "PS-EditorAttribute_Marker_UseWorldScale_Description"
   Modified 1593489050
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFD5803FAF5569D}" {
   Id "PS-EditorAttribute_Marker_VisibleForEmptyFaction"
   Target_en_us "Visible for empty faction"
   Modified 1593662479
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{5EFD5803FE9D923D}" {
   Id "PS-EditorAttribute_Marker_VisibleForEmptyFaction_Description"
   Modified 1593662468
   Author "zazul"
   LastChanged "zazul"
  }
 }
}